"""
Video segment implementation.
"""

from dataclasses import dataclass, field
from typing import Any, Optional, Dict, TYPE_CHECKING

from .base import Segment

if TYPE_CHECKING:
    from video_toolkit.config import ProjectConfig
    from video_toolkit.sources import ContentSource


@dataclass
class VideoSegment(Segment):
    """
    Video segment with content from a source.

    The source can be:
    - Asset: Static video file
    - Placeholder: Debug placeholder
    - FunctionGenerator: Programmatically generated
    - ScriptGenerator: Generated by external script
    """

    source: "ContentSource" = None
    scale: str = "fit"  # "fit", "fill", "stretch"
    loop: bool = False
    preserve_audio: bool = False

    def render(self, config: "ProjectConfig") -> Any:
        """
        Render this segment to a MoviePy clip.

        Args:
            config: Project configuration

        Returns:
            MoviePy VideoClip
        """
        if self.source is None:
            raise ValueError(f"VideoSegment {self.id} has no source")

        # Get clip from source
        clip = self.source.get_clip(config)

        # Apply duration if specified
        if self.duration is not None:
            if self.loop and hasattr(clip, "loop"):
                clip = clip.loop(duration=self.duration)
            else:
                clip = clip.with_duration(self.duration)

        # Apply scaling
        clip = self._apply_scaling(clip, config)

        return clip

    def _apply_scaling(self, clip: Any, config: "ProjectConfig") -> Any:
        """Apply scaling to fit target resolution."""
        target_w, target_h = config.dimensions
        clip_w, clip_h = clip.size

        if self.scale == "fit":
            # Scale to fit within bounds, maintaining aspect ratio
            scale_w = target_w / clip_w
            scale_h = target_h / clip_h
            scale = min(scale_w, scale_h)

            if scale != 1.0:
                clip = clip.resized(scale)

        elif self.scale == "fill":
            # Scale to fill bounds, cropping if necessary
            scale_w = target_w / clip_w
            scale_h = target_h / clip_h
            scale = max(scale_w, scale_h)

            if scale != 1.0:
                clip = clip.resized(scale)

            # Crop to target size
            clip = clip.cropped(
                x_center=clip.w / 2,
                y_center=clip.h / 2,
                width=target_w,
                height=target_h,
            )

        elif self.scale == "stretch":
            # Stretch to exact dimensions
            clip = clip.resized((target_w, target_h))

        return clip

    def get_duration(self, config: "ProjectConfig") -> float:
        """Get duration from source clip or explicit duration."""
        if self.duration is not None:
            return self.duration

        # Get from source
        clip = self.source.get_clip(config)
        return clip.duration
